app/mod_rps/controllers.py
"""
RPS Module's Controllers
"""
from flask import Blueprint, flash, redirect, render_template, request, url_for

from app.mod_auth.models import Staff
from app.mod_rps.models import Rps
from app.mod_rps.forms import RpsForm

from common import flash_code

MOD_RPS = Blueprint('rps', __name__, url_prefix='/rps/')


@MOD_RPS.route('<matakuliah_id>/<matakuliah_kode>/data', methods=['GET'])
def table(matakuliah_id, matakuliah_kode):
    """
    Return RPS Table Page
    """
    user = Staff.is_login()
    if user is None:
        return redirect(url_for('auth.login'))

    rpses = Rps.get_by_matakuliah_id(matakuliah_id)
    return render_template("rps/table.html", rpses=rpses, matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode)

@MOD_RPS.route('<matakuliah_id>/<matakuliah_kode>/baru', methods=['GET', 'POST'])
def create(matakuliah_id, matakuliah_kode):
    """
    Return Create Page
    """
    user = Staff.is_login()
    if user is None:
        return redirect(url_for('auth.login'))

    form = RpsForm(request.form)
    if form.validate_on_submit():
        rps = Rps(
            kompetensi_dasar=form.kompetensi_dasar.data,
            indikator_capaian=form.indikator_capaian.data,
            materi=form.materi.data,
            matakuliah_id=form.matakuliah_id.data
        )

        if rps.insert():
            flash(f"RPS berhasil disimpan", flash_code.SUCCESS)
            return redirect(url_for('rps.create', matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode))
        else:
            flash(f"Gagal menambahkan data, terjadi kesalahan", flash_code.DANGER)

    form.matakuliah_id.data = matakuliah_id
    return render_template("rps/form.html", form=form, page_title="Buat RPS Baru", matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode)

@MOD_RPS.route('<matakuliah_id>/<matakuliah_kode>/ubah/<rps_id>', methods=['GET', 'POST'])
def update(matakuliah_id, matakuliah_kode, rps_id):
    """
    Return Update Page
    """
    user = Staff.is_login()
    if user is None:
        return redirect(url_for('auth.login'))

    rps = Rps.get_by_id(rps_id)
    if rps is None:
        flash(f"Terjadi kesalahan, RPS tidak dapat ditemukan", flash_code.WARNING)
        return redirect(url_for('rps.table', matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode))

    form = RpsForm(request.form)
    if form.validate_on_submit():
        rps_update = Rps.update(
            rps_id=form.rps_id.data,
            kompetensi_dasar=form.kompetensi_dasar.data,
            indikator_capaian=form.indikator_capaian.data,
            materi=form.materi.data
        )
        if rps_update:
            flash(f"RPS telah berhasil diubah", flash_code.SUCCESS)
            return redirect(url_for("rps.update", matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode, rps_id=rps_id))
        else:
            flash(f"Terjadi kesalahan pada proses penyimpanan, data gagal diubah", flash_code.DANGER)
            form = RpsForm(
                data={
                    'rps_id': rps_id,
                    'matakuliah_id': matakuliah_id,
                    'kompetensi_dasar': form.kompetensi_dasar.data,
                    'indikator_capaian': form.indikator_capaian.data,
                    'materi': form.materi.data
                }
            )
    else:
        form = RpsForm(
            data={
                'rps_id': rps_id,
                'matakuliah_id': matakuliah_id,
                'kompetensi_dasar': rps.kompetensi_dasar,
                'indikator_capaian': rps.indikator_capaian,
                'materi': rps.materi
            }
        )
    return render_template("rps/form.html", form=form, page_title="Ubah RPS", matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode)

@MOD_RPS.route('<matakuliah_id>/<matakuliah_kode>/hapus/<rps_id>', methods=['GET'])
def delete(matakuliah_id, matakuliah_kode, rps_id):
    rps_delete = Rps.delete(rps_id)
    if rps_delete:
        flash(f"RPS telah berhasil dihapus", flash_code.SUCCESS)
        return redirect(url_for("rps.table", matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode))
    else:
        flash(f"Terjadi kesalahan, RPS gagal dihapus", flash_code.DANGER)
        return redirect(url_for("rps.update", matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode, rps_id=rps_id))

@MOD_RPS.route('<rps_id>/preprocess/simpan', methods=['POST'])
def store_preprocess(rps_id):
    """
    Store Preprocessed RPS
    """
    if request.method == 'POST':
        preprocessed_kompetensi = request.form['preprocessed_kompetensi']
        preprocessed_indikator = request.form['preprocessed_indikator']
        preprocessed_materi = request.form['preprocessed_materi']
        if Rps.store_preprocessed(rps_id, preprocessed_kompetensi, preprocessed_indikator, preprocessed_materi):
            return f'Berhasil disimpan'
    return f'Gagal melakukan penyimpanan'

app/templates/rps/form.html
{% extends "base.html" %}

{% block title %}{{ page_title }}{% endblock %}

{% block content_title %}{{ page_title }}{% endblock %}

{% block button_insert %}
<a href="{{ url_for('rps.table', matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode) }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
    &larr; Kembali ke Tabel RPS
</a>
{% endblock %}

{% block form_error %}
{% if form.errors %}
<!-- Content Row -->
<div class="row">
{% for field, error in form.errors.items() %}
    {% for e in error %}
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card mb-4 py-3 border-bottom-danger">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Terjadi Kesalahan</div>
                <div class="mb-0 text-gray-800">{{ e }}</div>
            </div>
            </div>
        </div>
        </div>
    </div>
    {% endfor %}
{% endfor %}
</div>
{% endif %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">{{ page_title }}</h6>
        </div>
        <div class="card-body">
          <form class="user"
            method="POST"
            accept-charset="UTF-8"
            role="form">

              {{ form.csrf_token }}

              {{ render_field(form.rps_id) }}
              {{ render_field(form.matakuliah_id) }}

              <div class="form-group">
                <label for="kode">Kompetensi Dasar:</label>
                {{ render_field(form.kompetensi_dasar, class="form-control form-control-user", placeholder="", maxlength="200") }}
              </div>

              <div class="form-group">
                <label for="kode">Indikator Capaian:</label>
                {{ render_field(form.indikator_capaian, class="form-control form-control-user", placeholder="", type="text", maxlength="200") }}
              </div>

              <div class="form-group">
                <label for="kode">Materi:</label>
                {{ render_field(form.materi, class="form-control form-control-user", placeholder="", type="text", maxlength="200") }}
              </div>

              <button class="btn btn-primary btn-user btn-block text-uppercase font-weight-bold" type="submit" name="submit">
                  Simpan
              </button>

              {% if page_title == 'Ubah RPS' %}
              <a href='{{ url_for("rps.delete", matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode, rps_id=form.rps_id.data) }}' 
                class="btn btn-danger btn-user btn-block text-uppercase font-weight-bold">
                  Hapus
              </a>
              {% endif %}
          </form>
        </div>
      </div>

    </div>
</div>
{% endblock %}

app/templates/rps/table.html
{% extends "base.html" %}

{% block title %}Tabel RPS{% endblock %}

{% block style_libs %}
<link href="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
{% endblock %}

{% block content_title %}RPS{% endblock %}

{% block button_insert %}
<a href="{{ url_for('rps.create', matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode) }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
    <i class="fas fa-plus fa-sm text-white-50"></i> Buat Data Baru
</a>
{% endblock %}

{% block content %}
<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Tabel RPS</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>No</th>
            <th>Kompetensi Dasar</th>
            <th>Indikator Capaian</th>
            <th>Materi</th>
            <th>Aksi</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>No</th>
            <th>Kompetensi Dasar</th>
            <th>Indikator Capaian</th>
            <th>Materi</th>
            <th>Aksi</th>
          </tr>
        </tfoot>
        <tbody>
          {% for rps in rpses %}  
          <tr>
            <td>{{ loop.index }}</td>
            <td>{{ rps.kompetensi_dasar }}</td>
            <td>{{ rps.indikator_capaian }}</td>
            <td>{{ rps.materi }}</td>
            <td>
                <a href="{{ url_for('rps.update', matakuliah_id=matakuliah_id, matakuliah_kode=matakuliah_kode, rps_id=rps.id) }}" class="btn btn-primary btn-user btn-block">Update</button>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
<!-- /.container-fluid -->
{% endblock %}

{% block scripts_libs %}
<!-- Page level plugins -->
<script src="{{ url_for('static', filename='vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

<!-- Page level custom scripts -->
<script src="{{ url_for('static', filename='js/demo/datatables-demo.js') }}"></script>
{% endblock %}