app/mod_auth/controllers.py
"""
Auth Module's Controllers
"""
from flask import Blueprint, flash, redirect, render_template, request, session, url_for

from app.mod_auth.forms import LoginForm
from app.mod_auth.models import Staff

from common import code, flash_code

MOD_AUTH = Blueprint('auth', __name__, url_prefix='/')


@MOD_AUTH.route('', methods=['GET', 'POST'])
def login():
    """
    Return a HTML of Landing Page.
    """
    if session.get('user_id') is not None:
        print(session.get('user_name'))
        flash("Anda sudah login", flash_code.INFO)
        return redirect(url_for('dashboard.dashboard'))
        
    form = LoginForm(request.form)
    if form.validate_on_submit():
        result = Staff.login(form.npk.data, form.password.data)
        if result["status"] == code.OK:
            staff = result["staff"]
            session['user_id'] = staff.id
            session['user_name'] = staff.nama
            flash("Anda berhasil masuk", flash_code.SUCCESS)
            return redirect(url_for('unit.table'))
        else:
            flash("NPK/Password anda tidak sesuai", flash_code.DANGER)
        # Register Purposes
        # staff = Staff(form.npk.data, form.password.data)
        # error = staff.insert()
        # if error:
        #     flash("Terjadi kesalahan", flash_code.DANGER)
        # else:
        #     flash("Data berhasil masuk", flash_code.SUCCESS)
        #     form = LoginForm()
    return render_template("auth/login.html", form=form)

@MOD_AUTH.route('/logout', methods=['GET'])
def logout():
    session.clear()
    flash('Berhasil logout', 'info')
    return redirect(url_for('auth.login'))

@MOD_AUTH.route('/password', methods=['GET'])
def password():
    user = Staff.is_login()
    if user is None:
        return redirect(url_for('auth.login'))
    return redirect(url_for('staff.password', staff_id=user.id, staff_npk=user.npk))

app/templates/base.html
{% macro render_field(field, placeholder=None) %} 
{% if field.errors %}
<div>
{% elif field.flags.error %}
<div>
{% else %}
<div>
{% endif %} 

{% set css_class = 'form-control ' + kwargs.pop('class', '') %} 
{{ field(class=css_class, placeholder=placeholder, **kwargs) }}
</div>
{% endmacro %}

{% block doc -%}
<!DOCTYPE html>
<html lang="en">
{%- block html %}
<head>
{%- block head %}
{%- block metas %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Library Procurement Web Application">
  <meta name="author" content="Ridho Febriansa">
{%- endblock metas %}

  <title>{% block title %}{{title|default}}{% endblock title %}</title>

  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='icons/apple-touch-icon.png') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='icons/favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='icons/favicon-16x16.png') }}">
  <link rel="manifest" href="{{ url_for('static', filename='icons/site.webmanifest') }}">

  {%- block styles %}
  <!-- Custom fonts for this template-->
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  {%- block sbadmin_css %}
  <link href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}" rel="stylesheet">
  {%- endblock sbadmin_css %}
  {%- endblock styles %}
  {%- block style_libs %}{%- endblock style_libs %}
{%- endblock head %}
</head>

<body {% block body_attribs %}id="page-top"{% endblock body_attribs %}>
{% block body -%}
  <!-- Page Wrapper -->
  <div id="wrapper">
    {% block navbar %}
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url_for('unit.table') }}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-book"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Library Procurement<sub>V2</sub></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('unit.table') }}">
          <i class="fas fa-fw fa-cog"></i>
          <span>Unit</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('staff.table') }}">
          <i class="fas fa-fw fa-cog"></i>
          <span>Staff</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('mahasiswa.table') }}">
          <i class="fas fa-fw fa-cog"></i>
          <span>Mahasiswa</span>
        </a>
      </li>

      <hr class="sidebar-divider my-0">

      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('matakuliah.table') }}">
          <i class="fas fa-fw fa-cog"></i>
          <span>Matakuliah</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('pengusulan.table') }}">
          <i class="fas fa-fw fa-cog"></i>
          <span>Pengusulan</span>
        </a>
      </li>

      <hr class="sidebar-divider my-0">

      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('buku.table') }}">
          <i class="fas fa-fw fa-cog"></i>
          <span>Buku</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('peminjaman.periode') }}">
          <i class="fas fa-fw fa-cog"></i>
          <span>Peminjaman</span>
        </a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">
    </ul>
    <!-- End of Sidebar -->
    {%- endblock navbar %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            {% set logged_name = session['user_name'] %}

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              {% if logged_name %}
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                  <i class="fas fa-user-circle fa-sm text-gray-600"></i> {{ logged_name }}
                </span>
              </a>
              {% else %}
              <a class="nav-link dropdown-toggle" href="{{ url_for('auth.login') }}" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                  <i class="fas fa-user-circle fa-sm text-gray-600"></i> Login
                </span>
              </a>
              {% endif %}
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{ url_for('auth.password') }}">
                  <i class="fas fa-cog fa-sm fa-fw mr-2 text-gray-400"></i>
                  Ubah Password
                </a>
                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        {% block page_content -%} 
        <div class="container-fluid">
          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{% block content_title -%}Dashboard{% endblock content_title -%}</h1>
            {% block button_insert -%}{% endblock button_insert -%}
          </div>

          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          <!-- Content Row -->
          <div class="row">
            {% for category, message in messages %}
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card mb-4 py-3 border-bottom-{{ category }}">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-{{ category }} text-uppercase mb-1">{{ category }}</div>
                      <div class="mb-0 text-gray-800">{{ message }}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          {% endif %}
          {% endwith %}

          {% block form_error -%}{% endblock form_error %}

          {% block content -%}{% endblock content -%}
        </div>
        <!-- /.container-fluid -->
        {%- endblock page_content %} 

      </div>
      <!-- End of Main Content -->

      {% block footer -%}
      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>&copy; <span id="currentYear">year</span> Library Procurement</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->
      {%- endblock footer %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

{%- endblock body %}
<!-- Bootstrap core JavaScript-->
<script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Core plugin JavaScript-->
<script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

<!-- Custom scripts for all pages-->
<script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>
{% block scripts_libs %}{%- endblock scripts_libs %}

{% block scripts %}
<script>
$( document ).ready(function() {
  const currentDate = new Date();
  const currentYear = currentDate.getFullYear();
  $("#currentYear").html(currentYear);
});
</script>
{%- endblock scripts %}
</body>
{%- endblock html %}
</html>
{% endblock doc -%}